import pandas as pd
from scipy import stats

if __name__ == '__main__':

    semester1 = '2017-2'
    semester2 = '2017-2'

    weeks = ['Week0', 'Week1', 'Week2', 'Week3', 'Week4', 'Week5', 'Week6', 'Week7', 'Week8']

    input_data1_bd1 = pd.read_csv('roc_values/' + semester1 + '/bd1.csv', index_col=0)
    input_data1_bd2 = pd.read_csv('roc_values/' + semester1 + '/bd2.csv', index_col=0)
    input_data1_bd3 = pd.read_csv('roc_values/' + semester1 + '/bd3.csv', index_col=0)
    input_data1_bd4 = pd.read_csv('roc_values/' + semester1 + '/bd4.csv', index_col=0)
    input_data1_bd5 = pd.read_csv('roc_values/' + semester1 + '/bd5.csv', index_col=0)
    input_data1_bd6 = pd.read_csv('roc_values/' + semester1 + '/bd6.csv', index_col=0)

    input_data1_bd1 = input_data1_bd1[weeks]
    input_data1_bd2 = input_data1_bd2[weeks]
    input_data1_bd3 = input_data1_bd3[weeks]
    input_data1_bd4 = input_data1_bd4[weeks]
    input_data1_bd5 = input_data1_bd5[weeks]
    input_data1_bd6 = input_data1_bd6[weeks]

    # # 2016-1
    # print("1: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['adaboost']).pvalue))
    # print("2: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['naive_bayes']).pvalue))
    # print("3: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['random_forest']).pvalue))
    # print("4: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['naive_bayes']).pvalue))
    # print("5: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['adaboost']).pvalue))
    # print("6: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['knn']).pvalue))
    # print("7: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['knn']).pvalue))
    # print("8: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['naive_bayes']).pvalue))
    # print("9: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['adaboost']).pvalue))
    # print("10: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['random_forest']).pvalue))
    # print("11: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['mlp']).pvalue))
    # print("12: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['naive_bayes']).pvalue))
    # print("13: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['random_forest']).pvalue))
    # print("14: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['knn']).pvalue))
    # print("15: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['adaboost']).pvalue))
    # print("16: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['knn']).pvalue))
    # print("17: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['random_forest']).pvalue))
    # print("18: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['adaboost']).pvalue))
    # print("19: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['mlp']).pvalue))
    # print("20: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['knn']).pvalue))
    # print("21: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['random_forest']).pvalue))
    # print("22: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['knn']).pvalue))
    # print("23: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['random_forest']).pvalue))
    # print("24: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['mlp']).pvalue))
    # print("25: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['mlp']).pvalue))
    # print("26: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['mlp']).pvalue))
    # print("27: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['mlp']).pvalue))
    # print("28: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['naive_bayes']).pvalue))
    # print("29: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['naive_bayes']).pvalue))

    # # 2016-2
    # print("1: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['adaboost']).pvalue))
    # print("2: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['random_forest']).pvalue))
    # print("3: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['naive_bayes']).pvalue))
    # print("4: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['adaboost']).pvalue))
    # print("5: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['adaboost']).pvalue))
    # print("6: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['random_forest']).pvalue))
    # print("7: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['knn']).pvalue))
    # print("8: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['adaboost']).pvalue))
    # print("9: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['knn']).pvalue))
    # print("10: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['random_forest']).pvalue))
    # print("11: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['random_forest']).pvalue))
    # print("12: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['naive_bayes']).pvalue))
    # print("13: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['adaboost']).pvalue))
    # print("14: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['mlp']).pvalue))
    # print("15: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['random_forest']).pvalue))
    # print("16: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['random_forest']).pvalue))
    # print("17: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['mlp']).pvalue))
    # print("18: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['mlp']).pvalue))
    # print("19: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['mlp']).pvalue))
    # print("20: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['mlp']).pvalue))
    # print("21: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['knn']).pvalue))
    # print("22: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['mlp']).pvalue))
    # print("23: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['knn']).pvalue))
    # print("24: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['naive_bayes']).pvalue))
    # print("25: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['knn']).pvalue))
    # print("26: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['naive_bayes']).pvalue))
    # print("27: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['naive_bayes']).pvalue))
    # print("28: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['knn']).pvalue))
    # print("29: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['naive_bayes']).pvalue))

    # # 2017-1
    # print("1: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['adaboost']).pvalue))
    # print("2: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['mlp']).pvalue))
    # print("3: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['knn']).pvalue))
    # print("4: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['mlp']).pvalue))
    # print("5: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['random_forest']).pvalue))
    # print("6: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['knn']).pvalue))
    # print("7: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['mlp']).pvalue))
    # print("8: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['naive_bayes']).pvalue))
    # print("9: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['adaboost']).pvalue))
    # print("10: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['knn']).pvalue))
    # print("11: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['mlp']).pvalue))
    # print("12: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['random_forest']).pvalue))
    # print("13: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['random_forest']).pvalue))
    # print("14: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['mlp']).pvalue))
    # print("15: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['adaboost']).pvalue))
    # print("16: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['mlp']).pvalue))
    # print("17: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['random_forest']).pvalue))
    # print("18: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['random_forest']).pvalue))
    # print("19: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['naive_bayes']).pvalue))
    # print("20: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['naive_bayes']).pvalue))
    # print("21: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['adaboost']).pvalue))
    # print("22: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['knn']).pvalue))
    # print("23: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['knn']).pvalue))
    # print("24: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['knn']).pvalue))
    # print("25: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['adaboost']).pvalue))
    # print("26: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['naive_bayes']).pvalue))
    # print("27: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['naive_bayes']).pvalue))
    # print("28: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['naive_bayes']).pvalue))
    # print("29: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['random_forest']).pvalue))

    # 2017-2
    print("1: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['adaboost']).pvalue))
    print("2: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['adaboost']).pvalue))
    print("3: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['random_forest']).pvalue))
    print("4: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['random_forest']).pvalue))
    print("5: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['random_forest']).pvalue))
    print("6: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['random_forest']).pvalue))
    print("7: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['random_forest']).pvalue))
    print("8: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['random_forest']).pvalue))
    print("9: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['adaboost']).pvalue))
    print("10: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['knn']).pvalue))
    print("11: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['knn']).pvalue))
    print("12: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['adaboost']).pvalue))
    print("13: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['adaboost']).pvalue))
    print("14: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['mlp']).pvalue))
    print("15: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['knn']).pvalue))
    print("16: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['mlp']).pvalue))
    print("17: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['mlp']).pvalue))
    print("18: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['mlp']).pvalue))
    print("19: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['knn']).pvalue))
    print("20: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['knn']).pvalue))
    print("21: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['knn']).pvalue))
    print("22: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['naive_bayes']).pvalue))
    print("23: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd2.loc['naive_bayes']).pvalue))
    print("24: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd4.loc['naive_bayes']).pvalue))
    print("25: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd3.loc['mlp']).pvalue))
    print("26: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['naive_bayes']).pvalue))
    print("27: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd1.loc['mlp']).pvalue))
    print("28: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd6.loc['naive_bayes']).pvalue))
    print("29: " + str(stats.mannwhitneyu(input_data1_bd2.loc['adaboost'], input_data1_bd5.loc['naive_bayes']).pvalue))
    
